server:
  port: ${SERVICE_PORT}

discovery:
  service:
    name: ${DISCOVERY_SERVICE_NAME}
    port: ${DISCOVERY_SERVICE_PORT}
  dependencies: aldebaran-auth
  healthCheckPath: /monitor/health
  healthCheckInterval: ${DISCOVERY_HEALTH_CHECK_INTERVAL}
  consul:
    enabled: ${CONSUL_ENABLED}
    host: ${CONSUL_HOST}
    port: ${CONSUL_PORT}
  # temporary solution for presentational purposes
  aldebaran-auth:
    host: ${ALDEBARAN_AUTH_HOST}
    port: ${ALDEBARAN_AUTH_PORT}

api:
  defaultPage: 0
  defaultPageSize: 10
  maxFileLength: 10000000

spring:
  datasource:
    jdbcUrl: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/aldebaran?verifyServerCertificate=false&useSSL=true
    username: aldebaran-admin
    password: aldebaran-password
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    generate-ddl: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        hbm2ddl:
          auto: none

flyway:
  locations: classpath:db/migration/
  cleanOnValidationError: true
  validate-on-migrate: true
  revoked: true