service:
  address: ${EXPOSED_ADDRESS}
  port: ${EXPOSED_PORT}

server:
  port: ${SERVICE_PORT}

spring:
  datasource:
    jdbcUrl: jdbc:mysql://localhost:3306/aldebaran-auth?verifyServerCertificate=false&useSSL=true
    username: aldebaran-auth-admin
    password: aldebaran-auth-password
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    generate-ddl: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        hbm2ddl:
          auto: none

flyway:
  locations: classpath:db/migration/
  cleanOnValidationError: true
  validate-on-migrate: true
  revoked: true

jwt:
  header: Authorization
  issuer: aldebaran-auth
  defaultTokenLife: 10000
  encrypt: false
  encryption:
    key: dasdasdadashfdjt674gdgdggdfgdfggdasdasdadashfdjt674gdgdggdfgdfgg
  signature:
    key: dasdasdadashfdjt674gdgdggdfgdfggdasdasdadashfdjt674gdgdggdfgdfgg