VAGRANTFILE_API_VERSION = "2"
LOCAL_IP = "192.168.33.10"


DB_NAME="aldebaran"
DB_USER="aldebaran-admin"
DB_PASSWORD="aldebaran-password"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	config.vm.box = "packer-ubuntu"
	config.vm.box_url = "../../packer/build/ubuntu-16.10-amd64.box"

    config.vm.synced_folder ".", "/vagrant", disabled: false

	config.vm.network "private_network", ip: LOCAL_IP

	config.vm.network "forwarded_port", guest: 80, host: 8080
	config.vm.network "forwarded_port", guest: 3306, host: 3306
	config.vm.network "forwarded_port", guest: 8500, host: 8500

	config.vm.provider "virtualbox" do |vb|
		vb.gui = false
		vb.name = "aldebaran-vm-dist"
		vb.memory = "2048"
		vb.cpus = 2
	end

	config.vm.provision "shell", run: "once" do |s|
		s.path = "provisioning/before-docker-setup.sh"
	end
		
	config.vm.provision "shell", run: "once" do |s|
		s.path = "provisioning/run-aldebaran.sh"		  
	end
end
