VAGRANTFILE_API_VERSION = "2"
LOCAL_IP = "192.168.33.10"

DB_ROOT_PASSWORD="root"
GRAFANA_ADMIN_PASSWORD="admin"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	config.vm.box = "packer-ubuntu"
	config.vm.box_url = "../../packer/build/ubuntu-16.10-amd64.box"

    config.vm.synced_folder ".", "/vagrant", disabled: false

	config.vm.network "private_network", ip: LOCAL_IP
	config.vm.network "forwarded_port", guest: 3000, host: 3000
	config.vm.network "forwarded_port", guest: 3306, host: 3306
	config.vm.network "forwarded_port", guest: 6379, host: 6379
	config.vm.network "forwarded_port", guest: 8500, host: 8500
	config.vm.network "forwarded_port", guest: 9090, host: 9090
	config.vm.network "forwarded_port", guest: 9091, host: 9091

	config.vm.provider "virtualbox" do |vb|
		vb.gui = false
		vb.name = "aldebaran-vm"
		vb.memory = "3072"
		vb.cpus = 2
	end

	config.vm.provision "shell", run: "once" do |s|
		s.path = "provisioning/before-docker-setup.sh"
	end

    config.vm.provision "docker", run: "once" do |d|
        d.run "mysql",
            args: "-p 3306:3306 " +
				  "-v /var/mysql/data:/var/lib/mysql " +
				  "-v /vagrant/mysql/:/docker-entrypoint-initdb.d " +
                  "-e MYSQL_ROOT_PASSWORD='#{DB_ROOT_PASSWORD}' " +                
                  "--name mysql-server"
        d.run "redis",
            args: "-p 6379:6379 " +
                  "--name redis-server"
        d.run "consul",
            args: "-p 8500:8500 " +
                  "--name consul-server"
        d.run "prom/prometheus",
            args: "-p 9090:9090 " +
				  "-v /vagrant/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml " +
				  "--link consul-server:consul " +
                  "--name prometheus-server"
        d.run "grafana/grafana",
            args: "-p 3000:3000 " +
                  "-e GF_SECURITY_ADMIN_PASSWORD=#{GRAFANA_ADMIN_PASSWORD} " +
                  "--link prometheus-server:prometheus " +
                  "--name grafana-server"
    end
end
