VAGRANTFILE_API_VERSION = "2"
LOCAL_IP = "192.168.33.10"

DB_ROOT_PASSWORD="root"
GRAFANA_ADMIN_PASSWORD="admin"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	config.vm.box = "packer-ubuntu"
	config.vm.box_url = "../../packer/build/ubuntu-16.10-amd64.box"

    config.vm.synced_folder ".", "/vagrant", disabled: false

	config.vm.network "private_network", ip: LOCAL_IP
	config.vm.network "forwarded_port", guest: 3000, host: 3000
	config.vm.network "forwarded_port", guest: 3306, host: 3306
	config.vm.network "forwarded_port", guest: 4560, host: 4560
	config.vm.network "forwarded_port", guest: 5601, host: 5601
	config.vm.network "forwarded_port", guest: 6379, host: 6379
	config.vm.network "forwarded_port", guest: 8500, host: 8500
	config.vm.network "forwarded_port", guest: 9090, host: 9090
	config.vm.network "forwarded_port", guest: 9091, host: 9091	

	config.vm.provider "virtualbox" do |vb|
		vb.gui = false
		vb.name = "aldebaran-vm"
		vb.memory = "3072"
		vb.cpus = 2
	end

	config.vm.provision "shell", run: "once" do |s|
		s.path = "provisioning/before-docker-setup.sh"
	end

	config.vm.provision "shell", run: "once" do |s|
		s.path = "provisioning/run.sh"
	end
end
