VAGRANTFILE_API_VERSION = "2"
LOCAL_IP = "192.168.33.10"


DB_NAME="aldebaran"
DB_USER="aldebaran-admin"
DB_PASSWORD="aldebaran-password"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	config.vm.box = "packer-ubuntu"
	config.vm.box_url = "../../packer/build/ubuntu-16.10-amd64.box"

    config.vm.synced_folder ".", "/vagrant", disabled: true

	config.vm.network "private_network", ip: LOCAL_IP	
	config.vm.network "forwarded_port", guest: 3306, host: 3306
	
	config.vm.provider "virtualbox" do |vb|
		vb.gui = false
		vb.name = "aldebaran-vm"
		vb.memory = "1024"
		vb.cpus = 1
	end

	config.vm.provision "shell", run: "once" do |s|
		s.path = "provisioning/before-docker-setup.sh"
	end
	
	config.vm.provision "docker", run: "once" do |d|
		d.run "mysql",
			args: "-p 3306:3306 -v /var/mysql/data:/var/lib/mysql " +
			      "-e MYSQL_ROOT_PASSWORD='#{DB_PASSWORD}' " +
			      "-e MYSQL_USER='#{DB_USER}' " +
			      "-e MYSQL_PASSWORD='#{DB_PASSWORD}' " +
			      "-e MYSQL_DATABASE='#{DB_NAME}' " +
			      "--name mysql-server"
	end
end
